<html>
<head>
<?php echo SYS_HEAD; ?>
<script type="text/javascript">
var user_id = <?php echo $this->user_id?>;
var admin = <?php echo $this->admin;?>;

Ext.require([
    'Ext.*'
]);

Ext.define('Selection', {
    extend: 'Ext.data.Model',
    fields: [{name: 'id', type: 'int'},
             {name: 'currency_id', type: 'int'},
             {name: 'currency'},
             {name: 'mpq', type: 'int'},
             {name: 'moq', type: 'int'},
             {name: 'code'},
             {name: 'name'},
             {name: 'symbol'},
             {name: 'text'},
             {name: 'rate'},
             {name: 'description'}]
});

// 客户列表
var customerStore = Ext.create('Ext.data.Store', {
    model: 'Selection',
    proxy: {
        type: 'ajax',
        reader: 'json',
        url: homePath+'/public/erp/bpartner/getpartner/option/list/type/1'
    },
    autoLoad: true
});

// 客户渲染
var customerRender = function(val){
    if(val > 0){
        index = customerStore.findExact('id',val);
        if (index != -1){
            rs = customerStore.getAt(index).data;
            return rs.name;
        }
        return val;
    }else{
        return '无';
    }
}

// 币种
var currencyStore = Ext.create('Ext.data.Store', {
    model: 'Selection',
    proxy: {
       type: 'ajax',
       reader: 'json',
       url: homePath+'/public/erp/setting_currency/getcurrency/option/list'
    },
    autoLoad: true
});

var employeeListStore = Ext.create('Ext.data.Store', {
    model: 'Selection',
    proxy: {
         type: 'ajax',
         reader: 'json',
         url: homePath+'/public/admin/account/getuserlist'
    },
    autoLoad: true
});

// 数据模型
Ext.define('Price', {
    extend: 'Ext.data.Model',
    fields: [{name: "id"},
             {name: "review_state"},
             {name: "current_step"},
             {name: "last_step"},
             {name: "next_step"},
             {name: "to_finish"},
             {name: "can_review"},
             {name: "is_reviewer"},
             {name: "number"},
             {name: "state"},
             {name: "customer_id", type: "int"},
             {name: "customer_code"},
             {name: "customer_name"},
             {name: "currency"},
             {name: "tax_id", type: "int"},
             {name: "price_tax"},
             {name: "description"},
             {name: "remark"},
             {name: "review_info"},
             {name: "reviewer"},
             {name: "review_info_tip"},
             {name: "release_time"},
             {name: "create_time"},
             {name: "update_time"},
             {name: "create_user"},
             {name: "update_user"},
             {name: "creater"},
             {name: "updater"}]
});

// 数据源
var priceStore = Ext.create('Ext.data.Store', {
    model: 'Price',
    pageSize: 50,
    proxy: {
        type: 'ajax',
        reader: {
            type: 'json',
            root: 'rows',
            totalProperty: 'total'
        },
        url: homePath+'/public/erp/sale_price/get'
    },
    listeners: {
        beforeload: function(store){
        	var key = Ext.getCmp('search_key').getValue();
        	var state = Ext.getCmp('search_state').getValue();
            var date_from = Ext.Date.format(Ext.getCmp('search_date_from').getValue(), 'Y-m-d');
            var date_to = Ext.Date.format(Ext.getCmp('search_date_to').getValue(), 'Y-m-d');
            
            Ext.apply(store.proxy.extraParams, {
            	state: state,
                key: key,
                date_from: date_from,
                date_to: date_to
            });
        }
    }
});

var required = '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>';

var reviewInfoWin = Ext.create('Ext.window.Window', {
    title: '审核日志',
    border: 0,
    width: 400,
    modal: true,
    constrain: true,
    id: 'reviewInfoWin',
    layout: 'fit',
    maximizable: true,
    resizable: true,
    closeAction: 'hide',
    resizable: true,
    padding: 10,
    items: [{
        xtype: 'displayfield',
        id: 'reviewInfoView'
    }]
});

// 获取货币符号
function setMoney(val, currency){
    var symbol = '';
    
    currencyStore.each(function(rec) {
        if (rec.get('name') == currency) {
            symbol = rec.get('symbol');
        }
    });
    
    return Ext.util.Format.currency(val, symbol, 4);
}

// 货币格式化
function setTotalMoney(val, currency){
    var symbol = '';
    
    currencyStore.each(function(rec) {
        if (rec.get('name') == currency) {
            symbol = rec.get('symbol');
        }
    });
    
    return Ext.util.Format.currency(val, symbol, 2);
}

// 查看审核日志
function viewReviewInfo(info)
{
    reviewInfoWin.show();
    
    Ext.getCmp('reviewInfoView').setValue(info.replace(/>/g, '<br>'));
}

function reviewPrice(){
    Ext.getCmp('reviewPriceWin').show();

    var form = Ext.getCmp('price_form').getForm();
    
    Ext.getCmp('review_id').setValue(form.findField('id').getValue());
    Ext.getCmp('review_current_step').setValue(form.findField('current_step').getValue());
    Ext.getCmp('review_last_step').setValue(form.findField('last_step').getValue());
    Ext.getCmp('review_to_finish').setValue(form.findField('to_finish').getValue());
    Ext.getCmp('review_next_step').setValue(form.findField('next_step').getValue());
}
</script>
<script type="text/javascript" src="<?php echo HOME_PATH?>/application/modules/erp/views/scripts/sale/price/js/review.js"></script>
<script type="text/javascript" src="<?php echo HOME_PATH?>/application/modules/erp/views/scripts/sale/price/js/price.js"></script>
<script type="text/javascript" src="<?php echo HOME_PATH?>/application/modules/erp/views/scripts/sale/price/js/select.js"></script>
<script type="text/javascript">
// 显示查看窗口
function openPriceWin(idx){
	var form = priceForm.getForm();
    priceWin.show();
    form.reset();
    var record = priceStore.getAt(idx);
    form.loadRecord(record);
    Ext.getCmp('priceSaveBtn').disable();
    Ext.getCmp('itemsAddBtn').disable();
    Ext.getCmp('itemsDeleteBtn').disable();
    form.findField('operate').setValue('');
    
    itemsStore.load({
        params: {
        	price_id: record.get('id')
        }
    });

    if(record.get('can_review') == 1){
        Ext.getCmp('priceReviewBtn').enable();
    }else{
        Ext.getCmp('priceReviewBtn').disable();
    }

    form.getFields().each(function(field) {
        field.setReadOnly(true);
    });

    itemsGrid.getSelectionModel().clearSelections();
    ladderStore.loadData([],false);
}

var attachWin = Ext.create('Ext.window.Window', {
    title: '附件',
    modal: true,
    constrain: true,
    closeAction: 'hide',
    layout: 'fit',
    fieldDefaults: {
        labelAlign: 'left',
        labelWidth: 90,
        anchor: '100%'
    },
    items: [Ext.create('Ext.form.Panel', {
        id: 'attachForm',
        border: 0,
        url: homePath+'/public/erp/sale_price/editattach',
        bodyPadding: '2 2 0',
        fieldDefaults: {
            msgTarget: 'side',
            labelAlign: 'right',
            labelWidth: 60,
            anchor: '100%'
        },
        items: [{
            xtype: 'hiddenfield',
            name: 'price_id'
        }, {
            xtype: 'filefield',
            name: 'attach_file',
            allowBlank: false,
            fieldLabel: '附件',
            buttonText: '选择文件'
        }]
    })],
    buttons: [{
        text: '提交',
        handler: function() {
            var form = Ext.getCmp('attachForm').getForm();

            if(form.isValid()){
                form.submit({
                    waitMsg: '提交中，请稍后...',
                    success: function(form, action) {
                        var data = action.result;

                        if(data.success){
                            form.reset();
                            attachWin.hide();
                            priceStore.loadPage(1);
                        }else{
                            Ext.MessageBox.alert('错误', data.info);
                        }
                    },
                    failure: function(response){
                        Ext.MessageBox.alert('错误', '保存提交失败');
                    }
                });
            }
        }
    }, {
        text: '取消',
        handler: function() {
            Ext.getCmp('attachForm').getForm().reset();
            attachWin.hide();
        }
    }]
});

// 列表
var priceGrid = Ext.define('KitchenSink.view.grid.LockingGrid', {
    extend: 'Ext.grid.Panel',
    xtype: 'locking-grid',
    border: 0,
    store: priceStore,
    id: 'priceGrid',
    columnLines: true,
    tbar: [{
        xtype: 'datefield',
        format: 'Y-m-d',
        width: 100,
        id: 'search_date_from',
        emptyText: '创建从...'
    }, {
        xtype: 'datefield',
        format: 'Y-m-d',
        width: 100,
        id: 'search_date_to',
        emptyText: '创建至...'
    }, {
        xtype: 'combobox',
        id: 'search_state',
        value: 0,
        editable: false,
        displayField: 'text',
        valueField: 'val',
        width: 70,
        store: Ext.create('Ext.data.Store', {
            fields: ['text', 'val'],
            data: [
                {"text": "审核中", "val": 0},
                {"text": "拒绝", "val": 1},
                {"text": "已批准", "val": 2}
            ]
        }),
        listeners: {
            change: function(){
            	priceStore.loadPage(1);
            }
        }
    }, {
        xtype: 'textfield',
        id: 'search_key',
        emptyText: '关键字...',
        width: 100,
        listeners: {
            specialKey :function(field,e){
                if (e.getKey() == Ext.EventObject.ENTER){
                	priceStore.loadPage(1);
                }
            }
        }
    }, {
        text: '查询',
        iconCls: 'icon-search',
        handler: function(){
        	priceStore.loadPage(1);
        }
    }, {
        xtype: 'splitbutton',
        text: '新建',
        iconCls: 'icon-doc',
        handler: function(){
            var form = priceForm.getForm();
            form.reset();
            Ext.getCmp('priceReviewBtn').disable();
            Ext.getCmp('priceSaveBtn').enable();
            Ext.getCmp('itemsAddBtn').enable();
            Ext.getCmp('itemsDeleteBtn').enable();
            Ext.getCmp('priceSaveBtn').setText('提交');
            itemsStore.loadData([],false);
            
            form.findField('operate').setValue('new');

            form.getFields().each(function(field) {
                field.setReadOnly(false);
            });
            
            priceWin.show();

            ladderStore.loadData([],false);
            itemsGrid.getSelectionModel().clearSelections();
        },
        menu: [{
            text: '修改',
            tooltip: '针对被拒绝申请',
            iconCls: 'icon-edit',
            handler: function(){
                var selection = Ext.getCmp('priceGrid').getView().getSelectionModel().getSelection();

                if(selection.length == 0){
                    Ext.MessageBox.alert('错误', '没有选择修改对象！');
                }else if(selection[0].get('state') != 1){
                    Ext.MessageBox.alert('错误', '只允许编辑被拒绝的申请！');
                }else if(admin == 0 && selection[0].get('create_user') != user_id){
                    Ext.MessageBox.alert('错误', '没有权限修改当前申请！');
                }else{
                	var form = priceForm.getForm();
                	form.reset();
                    var record = selection[0];
                    form.loadRecord(record);
                    Ext.getCmp('priceSaveBtn').enable();
                    Ext.getCmp('itemsAddBtn').enable();
                    Ext.getCmp('itemsDeleteBtn').enable();
                    Ext.getCmp('priceReviewBtn').disable();
                    Ext.getCmp('priceSaveBtn').setText('保存');
                    form.findField('operate').setValue('edit');

                    form.getFields().each(function(field) {
                        field.setReadOnly(false);
                    });
                    
                    priceWin.show();
                    
                    itemsStore.load({
                        params: {
                        	price_id: record.get('id')
                        }
                    });
                }
            }
        }]
    }, {
        text: '审核',
        tooltip: '审核前请选择需要审核的申请',
        disabled: true,
        id: 'reviewBtn',
        iconCls: 'icon-accept',
        handler: function(){
            var selection = Ext.getCmp('priceGrid').getView().getSelectionModel().getSelection();

            if(selection.length == 0){
                Ext.MessageBox.alert('错误', '没有选择审核对象！');
            }else if(selection[0].get('state') != 0){
                Ext.MessageBox.alert('错误', '当前申请不允许审核！');
            }else{
            	var form = priceForm.getForm();
                var record = selection[0];
                form.reset();
                form.loadRecord(record);
                reviewForm.getForm().reset();
                Ext.getCmp('priceSaveBtn').disable();
                Ext.getCmp('itemsAddBtn').disable();
                Ext.getCmp('itemsDeleteBtn').disable();
                Ext.getCmp('priceReviewBtn').enable();
                form.findField('operate').setValue('');

                form.getFields().each(function(field) {
                    field.setReadOnly(true);
                });
                
                priceWin.show();
                priceWin.restore();
                
                itemsStore.load({
                    params: {
                    	price_id: record.get('id')
                    }
                });
            }
        }
    }, {
        text: '附件',
        id: 'attachBtn',
        tooltip: '选择申请上传附件',
        disabled: true,
        iconCls: 'icon-attach',
        handler: function(){
            attachWin.show();

            Ext.getCmp('attachForm').getForm().findField('price_id').setValue(Ext.getCmp('priceGrid').getView().getSelectionModel().getSelection()[0].get('id'));
        }
    }, '->', {
        text: '刷新',
        iconCls: 'icon-refresh',
        handler: function(){
        	priceStore.reload();
        }
    }],
    viewConfig: {
        stripeRows: false
    },
    columns: [{
        xtype: 'rownumberer'
    }, {
        text: 'ID',
        align: 'center',
        hidden: true,
        locked: true,
        dataIndex: 'id'
    }, {
        text: '编号',
        align: 'center',
        dataIndex: 'number',
        locked: true,
        width: 120
    }, {
        text: '客户代码',
        dataIndex: 'customer_code',
        width: 80
    }, {
        text: '客户名称',
        dataIndex: 'customer_name',
        width: 160
    }, {
        text: '状态',
        align: 'center',
        dataIndex: 'state',
        renderer: function(val, meta, record){
            if(val == 0){
                meta.style = 'background-color: #ffe2e2';
                return record.get('reviewer') + '：未审核';
            }else if(val == 1){
                meta.style = 'background-color: #FF4500';
                return '拒绝';
            }else{
                meta.style = 'background-color: #DFFFDF';
                return '已审核';
            }
        },
        width: 160
    }, {
        text: '审核阶段',
        dataIndex: 'review_state',
        renderer: function(val, cellmeta, record){
            //cellmeta.tdAttr = 'data-qtip="' + record.get('review_info_tip') + '"';
            return '<span style="cursor:pointer;" onclick="viewReviewInfo(\''+record.get('review_info')+'\');">'+val+'</span>';
        },
        width: 260
    }, {
        text: '申请人',
        dataIndex: 'creater',
        align: 'center',
        width: 80
    }, {
        text: '申请时间',
        dataIndex: 'create_time',
        align: 'center',
        width: 140
    }, {
        text: '附件',
        dataIndex: 'attach_name',
        renderer: function(val, cellmeta, record, rowIndex){
            if(val != '' && val != null){
                cellmeta.tdAttr = 'data-qtip="' + val + '"';
                return '<a target="_blank" href="../' + record.get('attach_path') + '">' + val + '</a>';
            }
        },
        width: 200
    }, {
        text: '描述',
        dataIndex: 'description',
        width: 200
    }, {
        text: '备注',
        dataIndex: 'remark',
        width: 300
    }, {
        text: '发布时间',
        dataIndex: 'release_time',
        align: 'center',
        width: 140
    }, {
        text: '审核日志',
        dataIndex: 'review_info',
        renderer: function(val, cellmeta, record){
            cellmeta.tdAttr = 'data-qtip="' + record.get('review_info_tip') + '"';
            return '<span style="cursor:pointer;" onclick="viewReviewInfo(\''+val+'\');">'+val+'</span>';
        },
        width: 300
    }, {
        text: '更新人',
        hidden: true,
        dataIndex: 'updater',
        align: 'center',
        width: 80
    }, {
        text: '更新时间',
        hidden: true,
        dataIndex: 'update_time',
        align: 'center',
        width: 140
    }],
    listeners: {
        selectionchange: function( sel, selected, eOpts ){
            if(selected.length > 0){
                if(selected[0].get('can_review') == 1){
                    Ext.getCmp('reviewBtn').enable();
                }else{
                    Ext.getCmp('reviewBtn').disable();
                }

                Ext.getCmp('attachBtn').enable();
            }else{
                Ext.getCmp('attachBtn').disable();
            }
        },
        itemdblclick: function( grid, record, item, index, e, eOpts ) {
            if(admin == 1 || record.get('can_review') == 1 || record.get('is_reviewer') == 1 ||　record.get('create_user') == user_id){
                openPriceWin(index);
            }else{
                Ext.MessageBox.alert('错误', '没有权限查看当前申请！');
            }
        }
    },
    bbar: Ext.create('Ext.PagingToolbar', {
        border: 0,
        store: priceStore,
        displayInfo: true,
        displayMsg: '显示 {0} - {1} 共 {2}',
        emptyMsg: "没有数据"
    })
});

Ext.onReady(function() {
    Ext.QuickTips.init();
    
    Ext.state.Manager.setProvider(Ext.create('Ext.state.CookieProvider'));
    
    Ext.create('Ext.Viewport', {
        layout: 'border',
        border: 0,
        items: [{
            region: 'center',
            layout: 'fit',
            border: 0,
            items: [priceGrid]
        }]
    });

    priceStore.loadPage(1);
});
</script>
</head>
<body>
</body>
</html>