<html>
<head>
<?php echo SYS_HEAD; ?>
<?php
	    $onceexportable = 1;

		if(Application_Model_User::checkPermissionByRoleName('BOM查询-批量导出')
		  || Application_Model_User::checkPermissionByRoleName('BOM查询-单个导出')
		  || Application_Model_User::checkPermissionByRoleName('BOM管理员')
		  || Application_Model_User::checkPermissionByRoleName('系统管理员')){
			$onceexportable = 0;
		}
?>
<script type="text/javascript" src="<?php echo HOME_PATH?>/public/js/common.js"></script>
<script type="text/javascript">
Ext.require([
    'Ext.*'
]);

Ext.onReady(function() {
    Ext.QuickTips.init();

    Ext.define('bom', {
    extend: 'Ext.data.Model',
    idProperty: 'sid',
    fields: [{ name: "sid" },
             { name: "id" },
             { name: "nid" },
             { name: "pid" },
             { name: "recordkey" },
             { name: "code" },
             { name: "name" },
             { name: "description" },
             { name: "qty" },
             { name: "ver" },
             { name: "partposition" },
             { name: "replace" },
             { name: "remark" },
             { name: "project_no_name" },
             { name: "bom_file" },
             { name: "state" },
             { name: "count" }
            ]
    });

    var explanded = new Array();
    var recordkey = "<?php if (isset($_GET['recordkey'])) echo $_GET['recordkey']; ?>";
    var treeStore = Ext.create('Ext.data.TreeStore', {
        model: 'bom',
        proxy: {
            type: 'ajax',
            reader: 'json',
            url: '<?php echo HOME_PATH; ?>/public/product/bomview/getlist/recordkey/' + recordkey
        },
        lazyFill: true
    });
    treeStore.load();

    var infoWin = Ext.create('Ext.window.Window', {
	    title: '器件位置',
	    modal: true,
	    id: 'infoWin',
	    layout: 'fit',
	    maximizable: true,
	    width: 400,
	    resizable: true,
	    closeAction: 'hide',
	    resizable: true,
	    padding: 10,
	    items: [{
	        xtype: 'displayfield',
	        id: 'infoWinPartposition'
	    }]
	});

    var treePanel = Ext.create('Ext.tree.Panel', {
        //loadMask: true,
        useArrows: false,
        rootVisible: false,
        border:0,
        layout: 'fit',
        store: treeStore,
        xtype: 'cell-editing',
        animate: false,
        viewConfig: {
            plugins: {
                ptype: 'treeviewdragdrop',
                containerScroll: true
            },
            getRowClass: function(record) {
                if(!record.get('active')){
                    // 当启用状态为false时，设置背景色
                    return 'gray-row';
                }else if(record.get('name') == '新类别'){
                    // 当新增部门未取名时，设置背景色
                    return 'light-red-row';
                }
            }
        },
        tbar: [{
            text: '全部展开',
            handler: function(){
	        	if(this.text == '全部展开') {
	        		treePanel.expandAll();
	        		this.setText('全部折叠');
	        	} else {
	        		treePanel.collapseAll();
	        		this.setText('全部展开');
	        	}
            }
        }, {
            text: '导出全部',
            scope: this,
            disabled: <?php echo $onceexportable ?>,
            handler: function(){
            	Ext.Msg.wait('加载中，请稍后...', '提示');
                Ext.Ajax.request({
                    url: '<?php echo HOME_PATH; ?>/public/product/bom/exportcsv',
                    params: {
	                	search_recordkey: recordkey,
                        source: 'list'
                    },
                    method: 'POST',
                    success: function(response, options) {
                        var url = '<?php echo HOME_PATH; ?>/public/dcc/download/downcsv/path/' + response.responseText;
                        Ext.Msg.hide();
                        window.open(url);
                    }
                });
            }
        }, {
            text: '导出已展开',
            scope: this,
            disabled: <?php echo $onceexportable ?>,
            handler: function(){
            	if(explanded.length == 0) {
            		Ext.MessageBox.alert('提示', 'BOM未展开！');
            		return;
            	}
            	Ext.Msg.wait('加载中，请稍后...', '提示');
                Ext.Ajax.request({
                    url: '<?php echo HOME_PATH; ?>/public/product/bom/exportcsv',
                    params: {
	                	search_recordkey: recordkey,
	                	explanded: Ext.JSON.encode(explanded),
                        source: 'list'
                    },
                    method: 'POST',
                    success: function(response, options) {
                        var url = '<?php echo HOME_PATH; ?>/public/dcc/download/downcsv/path/' + response.responseText;
                        Ext.Msg.hide();
                        window.open(url);
                    }
                });
            }
        }, {
            text: '升版状况',
            id: 'updDetailBtn',
            hidden: true,
            handler: function(){
            	alert(<?php echo $this->recordkey?>);
            	Ext.create('Ext.window.Window', {
                    title: 'BOM升版状况',
                    maximized: true,
                    maximizable: false,
                    layout: 'fit',
                    html: "<iframe src='<?php echo HOME_PATH; ?>/public/product/upddetail?recordkey=<?php echo $this->recordkey?>&code=<?php echo $this->code?>&ver=<?php echo $this->ver?>' frameborder=0 width=100% height=100%></iframe>"
                }).show();
            }
        }],
        columns: [{
            text: 'ID',
            width: 40,
            hidden: true,
            dataIndex: 'sid'
        }, {
            xtype: 'treecolumn',
            text: '物料代码',
            width: 240,
            sortable: true,
            dataIndex: 'code',
            renderer: function(value, p, record) {
            	if(value && record.get('ver')) {
            		return value + " " + "<b>V" + record.get('ver') + "</b>";
            	} else {
            		return value;
            	}
            }
        },{
            text: '状态',
            width: 80,
            dataIndex: 'state',
            renderer: showTitle
        },{
            text: '物料名称',
            width: 180,
            dataIndex: 'name',
            stopSelection: false
        },{
            text: '物料描述',
            width: 240,
            dataIndex: 'description',
            renderer: showTitle
        },{
            text: '产品型号',
            width: 180,
            dataIndex: 'project_no_name',
            renderer: showTitle
        },{
            text: '关联文件',
            width: 180,
            dataIndex: 'bom_file',
            renderer: showTitle
        },{
            text: '数量',
            width: 100,
            dataIndex: 'qty',
            renderer: showTitle
        },{
            text: '替代料',
            width: 200,
            dataIndex: 'replace',
            renderer: function(value, p) {
				if(!value) return "";
				if(value.indexOf(',') !== -1) {
					var first = value.substr(0, value.indexOf(',')+1);
					value = value.replace(first, "<b>" + first + "</b>");
				}
			    var tip = value.replace(/,/g, '<br />');
			    p.tdAttr = 'data-qtip="' + tip + '"';
			    return value;
			}
        },{
            text: '器件位置',
            width: 200,
            dataIndex: 'partposition',
            renderer: function(value, p) {
                if(value) {
                    return "<a href='javascript:showPart(\"" + value + "\")' title='" + value + "'>" + value + "</a>";
                }
            }
        },{
            text: '备注',
            width: 120,
            dataIndex: 'remark',
            renderer: showTitle
        }],
        listeners: {
            'itemclick': function(treeview, record, item, index, e, opts){
                treeview.toggleOnDblClick = false;
                if(!record.get('leaf')){
                    var selModel = treePanel.getSelectionModel();
                    var selDataModel = selModel.getLastSelected();
                    var selNode = treeStore.getNodeById(selDataModel.internalId);

                    selNode.expand();
                }
            },
            'cellclick': function(obj, td, cellIndex, record, tr, rowIndex, e, eOpts ) {
            	if(cellIndex == 6) {
            		var value = record.get('partposition');
            		var infoW = Ext.getCmp("infoWin");
            		var mod = parseInt(value.length / (infoW.width * 0.13));
	        		var r = "";
	        		var per = parseInt(value.length / mod);
	        		for(i = 0;i < mod-1; i++) {
	        			r += value.substr(i*per, per) + "<br>";
	        		}
	        		r += value.substr((mod-1)*per);
            		Ext.getCmp("infoWinPartposition").setValue(r);
            		infoWin.show();
            	}
            },
            'afteritemexpand': function( node, index, item, eOpts ) {
            	for(var i = 0;i < explanded.length; i++) {
            		if(explanded[i] == node.data.code) {
            			break;
            		}
            	}
            	explanded.push(node.data.code);
            },
            'afteritemcollapse': function( node, index, item, eOpts ) {
            	for(var i = 0;i < explanded.length; i++) {
            		if(explanded[i] == node.data.code) {
            			explanded.splice(i, 1);
            		}
            	}
            	var rootNode = treePanel.getRootNode();
            	var childNodes = rootNode.childNodes;
            	for(var i=0;i<childNodes.length;i++){
            	    if(childNodes[i].data.code == node.data.code) {
            	    	childNodes[i].collapseChildren(true);
            	        childNodes[i].eachChild(function(child) {
            	        	if(child.data.children) {
            	        		for(var k = 0;k < explanded.length; k++) {
				            		if(explanded[k] == child.data.code) {
				            			explanded.splice(k, 1);
				            		}
				            	}
            	        	}
            	        })
            	        break;
            	    }
            	}
            }
        }
    });

    Ext.create('Ext.container.Viewport', {
        layout: 'border',
        border:0,
        rtl: true,
        items: [{
            region: 'center',
            border:0,
            layout: 'fit',
            plain: true,
            items:[treePanel]
        }]
    });
});
function showPart(value) {
	Ext.MessageBox.show({
        title: '器件位置',
        value : value,
        width:400,
        height: 200,
        buttons: Ext.MessageBox.OK,
        multiline: true
    });
}
</script>
</head>
<body>
</body>
</html>