<html>
<head>
<?php echo SYS_HEAD; ?>
<?php 
$url = $this->url();
$paramStr = substr($url, strpos($url, 'user_id'));
$paramArr = explode('/', $paramStr);

$user_id = $paramArr['1'];
$key = $paramArr['3'];
?>
<script type="text/javascript">
var copyRight = '<?php echo SYS_COPYRIGHT?>';
var user_id = '<?php echo $user_id?>';
var key = '<?php echo $key?>';
</script>
<script type="text/javascript" src="<?php echo HOME_PATH?>/application/modules/home/views/scripts/login/js/form.js"></script>
<style type="text/css"> 
#warp {
    position: absolute;
    width:595px;
    height:265px;
    left:50%;
    top:50%;
    margin-left:-299px;
    margin-top:-186px;
}
.hr0{ height:1px;border:none;border-top:1px dashed #a0a0a0;}
</style> 
<script type="text/javascript">
Ext.require([
    'Ext.*'
]);

Ext.onReady(function() {
    Ext.QuickTips.init();
    resetPwdWin.show();
});
</script>
</head>
<body>
<div class="login-bg"></div>
</body>
</html>