<html>
    <head>
        <?php echo SYS_HEAD; ?>
        <?php 
            $user_session = new Zend_Session_Namespace('user');
            $user = $user_session->user_info['employee_id'];
        ?>
        <script type="text/javascript" src="<?php echo HOME_PATH ?>/public/js/function.js"></script>
        <script type="text/javascript" src="<?php echo HOME_PATH ?>/public/js/comboxtree.js"></script>
        <script type="text/javascript" src="<?php echo HOME_PATH ?>/public/js/createField.js"></script>
        <script type="text/javascript" src="<?php echo HOME_PATH ?>/public/js/models.js"></script>
        <script type="text/javascript" src="<?php echo HOME_PATH ?>/public/js/fileSelect.js"></script>
        <script type="text/javascript" src="<?php echo HOME_PATH ?>/public/js/downloadFile.js"></script>
        <script type="text/javascript" src="<?php echo HOME_PATH ?>/public/js/codeSelect.js"></script>
        <script type="text/javascript" src="<?php echo HOME_PATH ?>/public/js/codeFileSelect.js"></script>
        <script type="text/javascript" src="<?php echo HOME_PATH ?>/public/js/uploadify.js"></script>
        <script type="text/javascript" src="<?php echo HOME_PATH ?>/public/js/FileView.js"></script>
        <script type="text/javascript" src="<?php echo HOME_PATH ?>/public/js/common.js"></script>
        <script src="<?php echo HOME_PATH ?>/public/js/jquery-1.11.1.min.js"></script>
        <style type="text/css">
            .x-fieldset{border:1px solid #B5B8C8;display:block;}
            .x-fieldset-none{border:0;display:block;padding:0;}
            .x-grid-cell.myreview
            {
                background-color: #9fc;
            }
            .fileQueue {
            	height: 150px;
            	overflow: auto;
            	border: 1px solid #E5E5E5;
            	margin-bottom: 2px;
            }            
        </style>
        <script type="text/javascript">
            Ext.require([
             'Ext.*'
             ]);
            Ext.define('Ext.ux.CustomTrigger', {
                extend: 'Ext.form.field.Trigger',
                alias: 'widget.customtrigger',
                // override onTriggerClick
                onTriggerClick: function() {
                    Ext.Msg.alert('Status', 'You clicked my trigger!');
                }
            });

            // 扩展display，使其支持dataFormat和numberFormat
            Ext.override(Ext.form.field.Display, {
                getValue: function() {
                    return this.value;
                },
                setValue: function(v) {
                    this.value = v;
                    this.setRawValue(this.formatValue(v));
                    return this;
                },
                formatValue: function(v) {
                    if (this.dateFormat && Ext.isDate(v)) {
                        return Ext.util.Format.date(v, this.dateFormat);
                    }
                    if (this.numberFormat && typeof v === 'number') {
                        return Ext.util.Format.number(v, this.numberFormat);
                    }
                    return v;
                }
            });
            var sendwin;
            Ext.onReady(function() {
                Ext.QuickTips.init();

                Ext.define('type', {
                    extend: 'Ext.data.Model',
                    fields: ['id', 'code', 'autocode']
                });
                Ext.define('project', {
                    extend: 'Ext.data.Model',
                    fields: [{name: "id"},
                        {name: "name"}]
                });

                var typeStore = Ext.create('Ext.data.Store', {
                    model: 'type',
                    proxy: {
                        type: 'ajax',
                        reader: 'json',
                        url: '<?php echo HOME_PATH; ?>/public/dcc/type/gettypeforcode'
                    }
                });

                var categoryStore = Ext.create('Ext.data.Store', {
                    model: 'codemaster',
                    proxy: {
                        type: 'ajax',
                        reader: 'json',
                        url: '<?php echo HOME_PATH; ?>/public/dcc/type/getcodemaster/type/category'
                    },
                    autoLoad: true
                });

                var filesStore = Ext.create('Ext.data.Store', {
                    pageSize: 100,
                    model: 'files',
                    sorters: [{
				         property: 'state',
				         direction: 'DESC'
				     }],
                    proxy: {
                        type: 'ajax',
                        reader: {
                            root: 'topics',
                            totalProperty: 'totalCount'
                        },
                        url: '<?php echo HOME_PATH; ?>/public/dcc/edit/getfiles/method/edit'
                    },
                    autoLoad: false
                });

                var codemasterStore = Ext.create('Ext.data.Store', {
                    model: 'codemaster',
                    proxy: {
                        type: 'ajax',
                        reader: 'json',
                        url: '<?php echo HOME_PATH; ?>/public/dcc/mine/getreason'
                    },
                    autoLoad: true
                });

                var codeStore = Ext.create('Ext.data.Store', {
                    model: 'code',
                    pageSize: 100,
                    proxy: {
                        type: 'ajax',
                        reader: {
                            root: 'topics',
                            totalProperty: 'totalCount'
                        },
                        url: '<?php echo HOME_PATH; ?>/public/dcc/code/getcode'
                    },
                    autoLoad: false
                });

                var uploadStore = Ext.create('Ext.data.Store', {
                    model: 'upload',
                    sorters: [{
				         property: 'state',
				         direction: 'DESC'
				     }],
                    proxy: {
                        type: 'ajax',
                        reader: 'json',
                        url: '<?php echo HOME_PATH; ?>/public/dcc/upload/getfiles/type/1'
                    },
                    autoLoad: false
                });

                // 产品系列数据源
                var projectStore = Ext.create('Ext.data.Store', {
                    model: 'project',
                    proxy: {
                        type: 'ajax',
                        reader: 'json',
                        url: '<?php echo HOME_PATH; ?>/public/dcc/code/getproject'
                    },
                    autoLoad: true
                });

                var file_names, file_ids;
                var archive = 0;
                var full = 0;
                var required = '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>';

                // 文件号选择grid
                var codeSelect = Ext.create('Ext.grid.Panel', {
                    store: codeStore,
                    border:0,
                    selType: 'checkboxmodel',
                    columnLines: true,
                    tbar: [{
                            xtype: 'textfield',
                            id: 'search_code1',
                            emptyText: '文件号...',
                            listeners: {
                                specialKey: function(field, e) {
                                    if (e.getKey() == Ext.EventObject.ENTER) {
                                        codeStore.loadPage(1);
                                    }
                                }
                            }
                        }, {
                            xtype: 'textfield',
                            id: 'search_description1',
                            emptyText: '描述...',
                            listeners: {
                                specialKey: function(field, e) {
                                    if (e.getKey() == Ext.EventObject.ENTER) {
                                        codeStore.loadPage(1);
                                    }
                                }
                            }
                        }, {
                            text: '查询',
                            iconCls: 'icon-search',
                            handler: function() {
                                var search_code = Ext.getCmp('search_code1').getValue();
                                var search_description = Ext.getCmp('search_description1').getValue();

                                codeStore.baseParams = {
                                    search_code: search_code,
                                    search_description: search_description,
                                    search_state: 1
                                }
                                codeStore.loadPage(1);
                            }
                        }, {
                            text: '<font color="blue">选择</font>',
                            formBind: true,
                            handler: function() {
                                var myMask = new Ext.LoadMask(Ext.getBody(), {
                                    msg: '正在加载，请稍后！',
                                    removeMask: true //完成后移除
                                });
                                myMask.show();

                                var selection = codeSelect.getView().getSelectionModel().getSelection();

                                if (selection.length > 0) {
                                    var code = selection[0].get('code');
                                    Ext.Msg.wait('加载中，请稍后...', '提示');
                                    Ext.Ajax.request({
                                        url: '<?php echo HOME_PATH; ?>/public/dcc/edit/ver',
                                        params: {code: code},
                                        method: 'POST',
                                        success: function(response, options) {

                                            var data = Ext.JSON.decode(response.responseText);
                                            if (data.success) {
                                                Ext.getCmp('code').setValue(code);
                                                Ext.getCmp('ver').setValue(Number(data.ver).toFixed(1));

                                                createIntelligenceForm(formPanel, selection[0].get('model_id'), [2, 2]);
                                                Ext.Msg.hide();
                                            } else {
                                                Ext.MessageBox.alert('错误', '文件版本获取失败');
                                            }
                                            myMask.hide();
                                        },
                                        failure: function() {
                                            myMask.hide();
                                            Ext.MessageBox.alert('错误', '文件版本获取失败');
                                        }
                                    });

                                    winCode.hide();
                                } else {
                                    Ext.MessageBox.alert('错误', '没有选择对象！');
                                }

                            }
                        }, {
                            text: '取消',
                            handler: function() {
                                winCode.hide();
                            }
                        }],
                    columns: [{
                            xtype: 'rownumberer'
                        }, {
                            text: 'ID',
                            flex: .5,
                            hidden: true,
                            dataIndex: 'id'
                        }, {
                            text: '文件号',
                            flex: 1,
                            sortable: true,
                            dataIndex: 'code'
                        }, {
                            text: '项目号',
                            flex: 1,
                            dataIndex: 'project_name',
                            renderer: showTitle
                        }, {
                            text: '描述',
                            flex: 1.5,
                            dataIndex: 'description',
                            renderer: showTitle
                        }, {
                            text: '备注',
                            flex: 2,
                            dataIndex: 'remark',
                            renderer: showTitle
                        }, {
                            text: '申请人',
                            flex: 0.5,
                            dataIndex: 'creater'
                        }, {
                            text: '申请时间',
                            flex: 1,
                            hidden: true,
                            dataIndex: 'create_time',
                            renderer: Ext.util.Format.dateRenderer('Y-m-d H:i:s')
                        }, {
                            text: '更新人',
                            flex: 0.5,
                            hidden: true,
                            dataIndex: 'updater'
                        }, {
                            text: '更新时间',
                            flex: 1,
                            hidden: true,
                            dataIndex: 'update_time',
                            renderer: Ext.util.Format.dateRenderer('Y-m-d H:i:s')
                        }],
                    bbar: Ext.create('Ext.PagingToolbar', {
                        store: codeStore,
                        displayInfo: true,
                        displayMsg: '显示 {0} - {1} 共 {2}',
                        emptyMsg: "没有数据"
                    })
                });

                codeStore.on("beforeload", function() {
                    var search_code = Ext.getCmp('search_code1').getValue();
                    var search_description = Ext.getCmp('search_description1').getValue();

                    Ext.apply(codeStore.proxy.extraParams, {
                        search_code: search_code,
                        search_description: search_description
                    });
                });

                // 文件选择grid
                var uploadSelect = Ext.create('Ext.grid.Panel', {
                    store: uploadStore,
                    border:0,
                    selType: 'checkboxmodel',
                    columnLines: true,
                    tbar: [{
                            xtype: 'textfield',
                            id: 'search_name2',
                            emptyText: '文件号...',
                            listeners: {
                                specialKey: function(field, e) {
                                    if (e.getKey() == Ext.EventObject.ENTER) {
                                        uploadStore.loadPage(1);
                                    }
                                }
                            }
                        }, {
                            xtype: 'textfield',
                            id: 'search_description',
                            emptyText: '描述...',
                            listeners: {
                                specialKey: function(field, e) {
                                    if (e.getKey() == Ext.EventObject.ENTER) {
                                        uploadStore.loadPage(1);
                                    }
                                }
                            }
                        }, {
                            text: '查询',
                            iconCls: 'icon-search',
                            handler: function() {
                                var search_name = Ext.getCmp('search_name2').getValue();
                                var search_description = Ext.getCmp('search_description').getValue();

                                uploadStore.baseParams = {
                                    search_name: search_name,
                                    search_description: search_description,
                                    search_del: 0,
                                    search_archive: archive,
                                    full: full
                                }
                                uploadStore.loadPage(1);
                            }
                        }, {
                            text: '<font color="blue">选择</font>',
                            formBind: true,
                            handler: function() {
                                var selection = uploadSelect.getView().getSelectionModel().getSelection();

                                if (selection.length > 0) {
                                    var name = "";
                                    var id = "";
                                    for (var i = 0; i < selection.length; i++) {
                                        if (name) {
                                            name += " | ";
                                            id += ",";
                                        }
                                        name += selection[i].get('name');
                                        id += selection[i].get('id');
                                    }
                                    Ext.getCmp(file_names).setValue(name);
                                    Ext.getCmp(file_ids).setValue(id);

                                    winUpload.hide();
                                } else {
                                    Ext.MessageBox.alert('错误', '没有选择对象！');
                                }

                            }
                        }, {
                            text: '取消',
                            handler: function() {
                                winUpload.hide();
                            }
                        }],
                    columns: [{
                            xtype: 'rownumberer'
                        }, {
                            text: 'ID',
                            flex: .5,
                            hidden: true,
                            dataIndex: 'id'
                        }, {
                            text: '文件名称',
                            flex: 1.5,
                            sortable: true,
                            dataIndex: 'name',
                            renderer: showTitle
                        }, {
                            text: '文件类型',
                            flex: 0.8,
                            sortable: true,
                            dataIndex: 'type'
                        }, {
                            text: '共享给',
                            flex: 1.5,
                            dataIndex: 'share_name',
                            renderer: showTitle
                        }, {
                            text: '共享期间',
                            flex: 1,
                            dataIndex: 'share_time',
                            renderer: showTitle
                        }, {
                            text: '描述',
                            flex: 1.5,
                            dataIndex: 'description',
                            renderer: showTitle
                        }, {
                            text: '备注',
                            flex: 1,
                            dataIndex: 'remark',
                            renderer: showTitle
                        }, {
                            text: '上传者',
                            flex: 0.7,
                            hidden: true,
                            dataIndex: 'updater'
                        }, {
                            text: '上传时间',
                            flex: 1,
                            hidden: true,
                            dataIndex: 'upload_time',
                            renderer: Ext.util.Format.dateRenderer('Y-m-d H:i:s')
                        }]
                });

                uploadStore.on("beforeload", function() {
                    var search_name = Ext.getCmp('search_name2').getValue();
                    var search_description = Ext.getCmp('search_description').getValue();

                    Ext.apply(uploadStore.proxy.extraParams, {
                        search_name: search_name,
                        search_description: search_description,
                        search_del: 0,
                        search_archive: archive,
                        full: full
                    });
                });

                var winCode = new Ext.Window({
                    xtype: "window",
                    border:0,
                    title: '文件编码选择',
                    height: 500,
                    width: 840,
                    modal: true,
                    layout: 'fit',
                    closeAction: 'hide',
                    items: [codeSelect],
                    tools: [{
                            type: 'refresh',
                            tooltip: '刷新表格数据',
                            scope: this,
                            handler: function() {
                                codeStore.reload();
                            }
                        }]
                });

                var winUpload = new Ext.Window({
                    xtype: "window",
                    border:0,
                    title: '文件选择',
                    height: 400,
                    width: 1000,
                    modal: true,
                    layout: 'fit',
                    closeAction: 'hide',
                    items: [uploadSelect],
                    tools: [{
                            type: 'refresh',
                            tooltip: '刷新表格数据',
                            scope: this,
                            handler: function() {
                                uploadStore.reload();
                            }
                        }]
                });

                // 增加记录表单
                var formPanel = new Ext.form.Panel({
                    bodyPadding: 5,
                    border:0,
                    width: 840,
                    layout: 'form',
                    autoScroll: true,
                    waitMsgTarget: true,
                    fieldDefaults: {
                        labelAlign: 'left',
                        labelWidth: 85,
                        margin: '0 10 0 0',
                        msgTarget: 'side'
                    },
                    items: [{
                            xtype: 'fieldcontainer',
                            layout: 'hbox',
                            items: [{
                                    xtype: 'textfield',
                                    hidden: true,
                                    id: 'id',
                                    name: 'id'
                                }, {
                                    xtype: 'triggerfield',
                                    fieldLabel: '文件编码',
                                    afterLabelTextTpl: required,
                                    id: 'code',
                                    editable: false,
                                    name: 'code',
                                    flex: 1.3,
                                    allowBlank: false,
                                    triggerCls: 'x-form-search-trigger',
                                    onTriggerClick: function() {
                                        codeStore.load({params: {search_state: 1}});
                                        winCode.show();
                                    }
                                }, {
                                    xtype: 'textfield',
                                    fieldLabel: '版本',
                                    afterLabelTextTpl: required,
                                    id: 'ver',
                                    name: 'ver',
                                    flex: 0.7,
                                    allowBlank: false,
                                    regex: /^\d{1,2}\.\d(,\d{1,2}\.\d)*$/,
                                    listeners:{
                                    	change:function(obj, newValue, oldValue, eOpts) {
                                    		if(Number(newValue) > 1.0) {
                                    			Ext.getCmp("reason_type").show();
                                    			Ext.getCmp("reason").show();
                                    		} else {
                                    			Ext.getCmp("reason_type").hide();
                                    			Ext.getCmp("reason").hide();
                                    		}
                                    	}
                                    }
                                }, {
                                    xtype: 'textfield',
                                    id: 'state_old',
                                    name: 'state_old',
                                    hidden: true
                                }, {
                                    xtype: 'combobox',
                                    fieldLabel: '状态',
                                    afterLabelTextTpl: required,
                                    id: 'state',
                                    name: 'state',
                                    typeAhead: true,
                                    editable: false,
                                    flex: 1,
                                    triggerAction: 'all',
                                    displayField: 'text',
                                    valueField: 'val',
                                    value: 'Active',
                                    allowBlank: false,
                                    store: Ext.create('Ext.data.Store', {
                                        fields: ['text', 'val'],
                                        data: [
                                            {"text": "Active", "val": "Active"},
                                            {"text": "Obsolete", "val": "Obsolete"},
                                            {"text": "Return", "val": "Return"}]
                                    }),
                                    listeners: {
                                        change: function(obj, newValue, oldValue, eOpts) {
                                            if (oldValue && newValue == 'Return' && Ext.getCmp('state_old').getValue() != 'Reviewing' && Ext.getCmp('state_old').getValue() != 'Return') {
                                                Ext.MessageBox.alert('错误', "只能退回审核中的文件");
                                                Ext.getCmp('state').setValue(oldValue);
                                                return false;
                                            }
                                        }
                                    }
                                }, {
                                    xtype: 'datefield',
                                    format: 'Y-m-d',
                                    fieldLabel: '归档日',
                                    flex: 1,
                                    value: new Date(),
                                    name: 'archive_time'
                                }]
                        }, {
                            xtype: 'fieldcontainer',
                            layout: 'hbox',
                            items: [{
                                    xtype: 'triggerfield',
                                    fieldLabel: '文件',
                                    afterLabelTextTpl: required,
                                    id: 'name',
                                    editable: false,
                                    name: 'name',
                                    flex: 1,
                                    triggerCls: 'x-form-search-trigger',
                                    onTriggerClick: function() {
                                        var fileSelect = lib.dcc.FileSelect({store: uploadStore, returnId: 'file_ids', returnValue: 'name', grid: this.up('grid'), userid : <?=$user?>});
                                        fileSelect.show();
                                    }
                                }, {
                                    xtype: 'combobox',
                                    editable: true,
                                    fieldLabel: '产品型号',
                                    flex: 1,
                                    id: 'project_no',
                                    name: 'project_no',
                                    displayField: 'name',
                                    valueField: 'id',
                                    triggerAction: 'all',
                                    forceSelection: true,
                                    selectOnFocus:true,
                                    emptyText: '无',
                                    store: projectStore,
                                    queryMode: 'local'
                                }, {
                                    xtype: 'textfield',
                                    id: 'file_ids',
                                    name: 'file_ids',
                                    hidden: true
                                }, {
                                    xtype: 'textfield',
                                    fieldLabel: '关键字',
                                    hidden: true,
                                    flex: 2,
                                    emptyText: '关键字用于提高检索效率，多个关键字以空格分隔',
                                    name: 'tag'
                                }]
                        }, {
                            xtype: 'fieldcontainer',
                            layout: 'hbox',
                            items: [{
                                    fieldLabel: '是否需要外发',
                                    xtype: 'checkbox',
                                    checked: false,
                                    name: 'send_require'
                                }]
                        }, {
                            xtype: 'fieldcontainer',
                            layout: 'hbox',
                            items: [{
                                    xtype: 'combobox',
                                    fieldLabel: '更改原因类型',
                                    id: 'reason_type',
                                    name: 'reason_type',
                                    hidden: true,
                                    typeAhead: true,
                                    editable: false,
                                    triggerAction: 'all',
                                    displayField: 'text',
                                    valueField: 'id',
                                    flex: 2,
                                    store: codemasterStore
                                }, {
                                    xtype: 'textarea',
                                    fieldLabel: '更改原因描述',
                                    hidden: true,
                                    flex: 2,
                                    rows: 2,
                                    id: 'reason',
                                    name: 'reason'
                                }]
                        }, {
                            xtype: 'fieldcontainer',
                            layout: 'hbox',
                            items: [{
                                    xtype: 'textarea',
                                    fieldLabel: '文件描述',
                                    flex: 2,
                                    rows: 2,
                                    name: 'description'
                                }, {
                                    xtype: 'textarea',
                                    fieldLabel: '备注',
                                    flex: 2,
                                    rows: 2,
                                    name: 'remark'
                                }]
                        }, {
                            xtype: 'fieldcontainer',
                            layout: 'hbox',
                            items: [{
                                    xtype: 'textfield',
                                    fieldLabel: '项目信息',
                                    hidden: true,
                                    flex: 2,
                                    name: 'project_info'
                                }]
                        }, {
                            xtype: 'fieldcontainer',
                            layout: 'hbox',
                            items: [{
                                    xtype: 'textfield',
                                    fieldLabel: '编辑信息',
                                    flex: 2,
                                    name: 'edit_info'
                                }]
                        }
                    ]
                });

                var win = new Ext.Window({
                    xtype: "window",
                    border:0,
                    title: '增加记录',
                    autoheight: true,
                    maxHeight: 480,
                    width: 890,
                    modal: true,
                    layout: 'fit',
                    x: 200,
                    y: 60,
                    plain: true,
                    closable: false,
                    closeAction: 'hide',
                    items: [formPanel],
                    buttons: [{
                            text: '提交',
                            formBind: true,
                            handler: function() {
                                var form = formPanel.getForm();
                                var file = Ext.getCmp('name').getValue();
                                var c = Ext.getCmp('code').getValue();
//                                if (file.indexOf(c) == -1) {
//                                    Ext.MessageBox.alert('提示', '文件名称错误（必须包含文件号）！');
//                                    return false;
//                                }
                                if (1/*form.isValid()*/) {
                                    form.submit({
                                        waitMsg: '提交中，请稍后...',
                                        clientValidation: true,
                                        submitEmptyText: false,
                                        url: '<?php echo HOME_PATH; ?>/public/dcc/edit/save',
                                        success: function(form, action) {
                                            if (action.result.result) {
                                                Ext.MessageBox.alert('提示', action.result.info);
                                                filesStore.reload();
                                                removeIntelligenceField(formPanel);
                                                form.reset();
                                                win.hide();
                                            } else {
                                                Ext.MessageBox.alert('错误', action.result.info);
                                            }
                                        },
                                        failure: function(response) {
                                            Ext.MessageBox.alert('错误', action.result.info);
                                        }
                                    });
                                }
                            }
                        }, {
                            text: '取消',
                            handler: function() {
                                removeIntelligenceField(formPanel);
                                formPanel.getForm().reset();
                                win.hide();
                            }
                        }]
                });

                // 查看详情
                var viewForm = new Ext.form.Panel({
                    width: 800,
                    border:0,
                    bodyPadding: 5,
                    layout: 'form',
                    autoScroll: true,
                    waitMsgTarget: true,
                    fieldDefaults: {
                        labelAlign: 'right',
                        labelWidth: 85,
                        msgTarget: 'side'
                    },
                    items: [{
                            xtype: 'fieldset',
                            title: '基本信息',
                            baseCls: 'x-fieldset',
                            items: [{
                                    xtype: 'textfield',
                                    hidden: true,
                                    name: 'id'
                                }, {
                                    xtype: 'displayfield',
                                    fieldLabel: '文件编码',
                                    editable: false,
                                    name: 'code',
                                    width: 100
                                }, {
                                    id: 'fileField',
                                    baseCls: 'x-fieldset-none',
                                    xtype: 'fieldset',
                                    items: []
                                }, {
                                    xtype: 'displayfield',
                                    fieldLabel: '描述',
                                    name: 'description'
                                }, {
                                    xtype: 'displayfield',
                                    fieldLabel: '备注',
                                    name: 'remark'
                                }, {
                                    xtype: 'displayfield',
                                    fieldLabel: '关键字',
                                    name: 'tag'
                                }, {
                                    id: 'baseinfo',
                                    baseCls: 'x-fieldset-none',
                                    xtype: 'fieldset',
                                    items: []
                                }]
                        }, {
                            id: 'reviewForm_ownerField',
                            xtype: 'fieldset',
                            title: '自定义信息',
                            hidden: true,
                            items: []
                        }, {
                            id: 'reviewField',
                            xtype: 'fieldset',
                            title: '审批信息',
                            hidden: true,
                            items: []
                        }],
                    buttons: [{
                            text: '关闭',
                            handler: function() {
                                removeIntelligenceField(this.up('form'));
                                this.up('form').getForm().reset();
                                winView.hide();
                            }
                        }]
                });

                var fileSendForm = Ext.create('Ext.form.Panel', {
                    width: 600,
                    border:0,
                    bodyPadding: 5,
                    layout: 'form',
                    autoScroll: true,
                    waitMsgTarget: true,
                    fieldDefaults: {
                        labelAlign: 'left',
                        labelWidth: 80,
                        msgTarget: 'side'
                    },
                    items: [{
                            layout: 'column', //第一二行
                            border: 0,
                            items: [{
                                    columnWidth: 0.4,
                                    border: 0,
                                    layout: 'form',
                                    items: [{
                                            xtype: 'combobox',
                                            fieldLabel: '类别',
                                            afterLabelTextTpl: required,
                                            id: 'sendtype',
                                            name: 'sendtype',
		                                    typeAhead: true,
		                                    editable: false,
		                                    flex: 1,
		                                    triggerAction: 'all',
		                                    displayField: 'text',
		                                    valueField: 'val',
		                                    allowBlank: false,
                                            store: Ext.create('Ext.data.Store', {
                                                fields: ['text', 'val'],
                                                data: [
                                                    {"text": "内发", "val": "内发"},
                                                    {"text": "外发", "val": "外发"}]
                                            }),
                                            listeners: {
                                                change: function(obj, newValue, oldValue, eOpts) {
                                                    var osy = Ext.getCmp('outsendtype');
                                                    if (newValue == '外发') {
                                                        osy.setDisabled(false);
                                                        osy.show();
                                                    } else {
                                                        osy.setDisabled(true);
                                                        osy.hide();
                                                    }
                                                }
                                            }
                                        }]
                                }, {
                                    columnWidth: 0.6,
                                    border: 0,
                                    layout: 'form',
                                    items: [{
                                            xtype: 'combobox',
                                            fieldLabel: '外发类别',
                                            afterLabelTextTpl: required,
                                            id: 'outsendtype',
                                            name: 'outsendtype',
                                            typeAhead: true,
                                            hidden: true,
                                            editable: false,
                                            flex: 1,
                                            triggerAction: 'all',
                                            displayField: 'text',
                                            valueField: 'val',
                                            allowBlank: false,
                                            store: Ext.create('Ext.data.Store', {
                                                fields: ['text', 'val'],
                                                data: [
                                                    {"text": "供应商", "val": "供应商"},
                                                    {"text": "客户", "val": "客户"}]
                                            })
                                        }]
                                }]
                        }, {
                            xtype: 'textfield',
                            fieldLabel: '收件人',
                            afterLabelTextTpl: required,
                            msgTarget: 'side',
                            allowBlank: false,
                            name: 'to'
                        }, {
                            xtype: 'textfield',
                            fieldLabel: '抄送',
                            msgTarget: 'side',
                            name: 'cc'
                        }, {
                            xtype: 'textfield',
                            fieldLabel: '主题',
                            afterLabelTextTpl: required,
                            fieldWidth: 80,
                            allowBlank: false,
                            name: 'subject'
                        }, {
                            xtype: 'textfield',
                            fieldLabel: '文件ID',
                            hidden: true,
                            id: 'exfile_ids',
                            name: 'exfile_ids'
                        }, {
                            xtype: 'triggerfield',
                            fieldLabel: '文件',
                            afterLabelTextTpl: required,
                            editable: false,
                            name: 'exfile',
                            id: 'exfile',
                            allowBlank: false,
                            triggerCls: 'x-form-search-trigger',
                            onTriggerClick: function() {
                                //archive = 1;
                                full = 1;
                                uploadStore.removeAll();
                                //uploadStore.load({params: {search_archive: archive, search_del: 0, full: full}});
                                winUpload.show();
                            }
                        }, {
                            xtype: 'htmleditor',
                            fieldLabel: '正文',
                            afterLabelTextTpl: required,
                            allowBlank: false,
                            style: 'margin:0',
                            name: 'content'
                        }, {
                            xtype: 'textarea',
                            fieldLabel: '描述',
                            rows: 2,
                            name: 'remark'
                        }]
                });

                var winView = new Ext.Window({
                    xtype: "window",
                    border:0,
                    height: 500,
                    title: '查看记录',
                    layout: 'fit',
                    closable: false,
                    closeAction: 'hide',
                    items: [viewForm]
                });

                var viewAction = function(codePanel) {
                    var selection = codePanel.getSelectionModel().getSelection();
                    if (selection.length <= 0) {
                        Ext.MessageBox.alert('请注意', '请您选择要查看的记录！');
                    } else if (selection.length >= 2) {
                        Ext.MessageBox.alert('请注意', '不能同时查看多个数据！');
                    } else {
                        var grid = selection[0];
                        var fileView = lib.dcc.FileView({grid: grid, model: 'edit'});
                        fileView.show();
                    }
                }

                var codePanel = Ext.create('Ext.grid.Panel', {
                    store: filesStore,
                    border:0,
                    selType: 'checkboxmodel',
//                    stateful: true, //true为启用cookie保存grid状态
//                    stateId: "dcc-mine-index-cookie-grid", //这将被用于生成cookie的id
                    columnLines: true,
                    viewConfig: {
                        stripeRows: false, // 取消偶数行背景色
                        getRowClass: function(record) {
                            if ("Obsolete" == record.get('state')) {
                                // 当分类启用状态为false时，设置背景色
                                return 'dark-row';
                            }
                        }
                    },
                    tbar: [{
                            xtype: 'textfield',
                            id: 'search_tag',
                            width: 200,
                            emptyText: '模糊查询，多个关键字以空格隔开',
                            listeners: {
                            	specialKey :function(field,e){
                                    if (e.getKey() == Ext.EventObject.ENTER){
                                    	filesStore.loadPage(1);
                                    }
                                }
                            }
                        }, {
                            xtype: 'datefield',
                            format: 'Y-m-d',
                            width: 100,
                            id: 'search_archive_date_from',
                            emptyText: '归档日期从...'
                        }, {
                            xtype: 'datefield',
                            format: 'Y-m-j',
                            width: 100,
                            id: 'search_archive_date_to',
                            emptyText: '归档日期至...'
                        }, {
                            xtype: 'combobox',
                            emptyText: '文件类别...',
                            id: 'search_category',
                            name: 'search_category',
                            editable: true,
                            displayField: 'text',
                            valueField: 'id',
                            triggerAction: 'all',
                            lazyRender: true,
                            store: categoryStore,
                            queryMode: 'local',
                            width: 100
                        }, {
                            xtype: 'combobox',
                            id: 'search_state',
                            emptyText: '状态...',
                            width: 100,
                            store: [['Active', '已归档'], ['Obsolete', '旧版作废'], ['Reviewing', '审核中'], ['Return', '退回'], ['Deleted', '取消']]
                        }, {
                            xtype: 'splitbutton',
                            text: '查询',
                            iconCls: 'icon-search',
                            handler: function() {
                                var search_tag = Ext.getCmp('search_tag').getValue();
                                var search_state = Ext.getCmp('search_state').getValue();
                                var search_archive_date_from = Ext.getCmp('search_archive_date_from').getValue();
                                var search_archive_date_to = Ext.getCmp('search_archive_date_to').getValue();
                                var search_category = Ext.getCmp('search_category').getValue();
                                filesStore.baseParams = {
                                    search_tag: search_tag,
                                    search_state: search_state,
                                    search_archive_date_from: search_archive_date_from,
                                    search_archive_date_to: search_archive_date_to,
                                    search_category: search_category
                                };
                                filesStore.loadPage(1);
                            },
                            menu: [{
                                    text: '导出',
                                    iconCls: 'icon-export',
                                    handler: function() {
                                        var search_tag = Ext.getCmp('search_tag').getValue();
                                        var search_state = Ext.getCmp('search_state').getValue();
                                        var search_archive_date_from = Ext.getCmp('search_archive_date_from').getValue();
                                        var search_archive_date_to = Ext.getCmp('search_archive_date_to').getValue();
                                		var search_category = Ext.getCmp('search_category').getValue();

                                        Ext.Msg.wait('操作中，请稍后...', '提示');
                                        Ext.Ajax.request({
                                            url: '<?php echo HOME_PATH; ?>/public/dcc/edit/exportcsv',
                                            params: {
                                                search_tag: search_tag,
                                                search_state: search_state,
                                                search_archive_date_from: search_archive_date_from,
                                                search_archive_date_to: search_archive_date_to,
                                                source: 'list',
                                                search_category: search_category
                                            },
                                            method: 'POST',
                                            success: function(response, options) {
                                                var url = '<?php echo HOME_PATH; ?>/public/dcc/download/downcsv/path/' + response.responseText;
                                                Ext.Msg.hide();
                                                window.open(url);
                                            }
                                        });
                                    }
                                }]
                        }, {
                            text: '增加记录',
                            scope: this,
                            handler: function() {
                                file_names = "name";
                                file_ids = "file_ids";
                                Ext.getCmp("project_no").hide();
                                win.setTitle("增加文件")
                                win.show();
                            }
                        }, {
                            text: '编辑',
                            scope: this,
                            handler: function() {
                                var selection = codePanel.getView().getSelectionModel().getSelection();
                                if (selection.length <= 0) {
                                    Ext.MessageBox.alert('请注意', '请您选择要编辑的记录！');
                                } else if (selection.length >= 2) {
                                    Ext.MessageBox.alert('请注意', '不能同时编辑多个数据！');
                                } else {
                                    win.setTitle("编辑文件")
                                    file_names = "name";
                                    file_ids = "file_ids";
                                    var grid = selection[0];
                                    formPanel.getForm().reset();
                                    formPanel.getForm().loadRecord(grid);
                                    Ext.getCmp("project_no").show();

                                    Ext.getCmp('state_old').setValue(grid.data.state);
                                    Ext.getCmp('state').setValue(grid.data.state);

                                    var model = grid.get('model_id');
                                    createIntelligenceForm(formPanel, model, [2, 2], false);

                                    var menu = "oa_doc_files_" + grid.get('id');
                                    // 加载自定义表单
                                    Ext.Msg.wait('加载中，请稍后...', '提示');
                                    Ext.Ajax.request({
                                        url: '<?php echo HOME_PATH; ?>/public/dcc/edit/getformval',
                                        params: {menu: menu},
                                        method: 'POST',
                                        success: function(response, options) {
                                            var data = Ext.JSON.decode(response.responseText);
                                            for (var i = 0; i < data.length; i++) {
                                                var field = Ext.getCmp("intelligenceField" + data[i].attrid);
                                                if (field != undefined) {
                                                    field.setValue(data[i].value);
                                                }
                                            }
                                            win.show();
                                            Ext.Msg.hide();
                                        },
                                        failure: function(form, action) {
                                            Ext.MessageBox.alert('错误', action.result.info);
                                        }
                                    });
                                }
                            }
                        }, {
                            text: '删除记录',
                            scope: this,
                            handler: function() {
                                var selection = codePanel.getView().getSelectionModel().getSelection();

                                if (selection.length > 0) {

                                    // 格式正确则提交修改数据
                                    Ext.MessageBox.confirm('确认', '确定删除所选内容？', function(button, text) {
                                        if (button === 'yes') {
                                            filesStore.remove(selection);

                                            var deleteRecords = filesStore.getRemovedRecords();

                                            var changeRows = {
                                                deleted: []
                                            }

                                            for (var i = 0; i < deleteRecords.length; i++) {
                                                changeRows.deleted.push(deleteRecords[i].data)
                                            }

                                            var json = Ext.JSON.encode(changeRows);
                                            Ext.Msg.wait('提交中，请稍后...', '提示');
                                            Ext.Ajax.request({
                                                url: '<?php echo HOME_PATH; ?>/public/dcc/edit/remove',
                                                params: {json: json},
                                                method: 'POST',
                                                success: function(response, options) {
                                                    var data = Ext.JSON.decode(response.responseText);

                                                    if (data.success) {
                                                        Ext.MessageBox.alert('提示', data.info);
                                                        filesStore.reload();
                                                    } else {
                                                        Ext.MessageBox.alert('错误', data.info);
                                                    }
                                                },
                                                failure: function(form, action) {
                                                    Ext.MessageBox.alert('错误', action.result.info);
                                                }
                                            });
                                        }
                                    });
                                } else {
                                    Ext.MessageBox.alert('错误', '没有选择删除对象！');
                                }
                            }
                        }, {
                            text: '批量下载',
                            handler: function() {
                            	var selection = codePanel.getView().getSelectionModel().getSelection();
                                if (selection.length <= 0) {
                                    Ext.MessageBox.alert('请注意', '请您选择要编辑的记录！');
                                } else {
                                	var ids = new Array();
                                    for (var i = 0; i < selection.length; i++) {
                                           ids.push(selection[i].data.id);
                                    }
                                    var url = '<?php echo HOME_PATH; ?>/public/dcc/files/downloadall/ids/' + ids.join(',');
                                    window.open(url);
                                }
                            }
                        }, {
                            text: '文件发放',
                            scope: this,
                            handler: function() {
                                /* file_names = "exfile";
                                file_ids = "exfile_ids";
                                var osy = Ext.getCmp('outsendtype');
                                osy.setDisabled(true);
                                osy.hide();

                                sendWin.show(); */
                                sendwin = Ext.create('Ext.window.Window', {
                                    title: '文件发放',
                                    height: 500,
                                    width: 1000,
                                    id : 'sendwin',
                                    constrain: true,
                                    layout: 'fit',
                                    html: "<iframe src='<?php echo HOME_PATH; ?>/public/dcc/send/filesend' frameborder=0 width=100% height=100%></iframe>"
                                });
                                sendwin.show();
                            }
                        }],
                    columns: [{
                            xtype: 'rownumberer'
                        }, {
                            text: 'ID',
                            flex: .5,
                            hidden: true,
                            dataIndex: 'id'
                        }, {
                            text: '文件号',
                            width: 130,
                            locked: true,
                            sortable: true,
                            dataIndex: 'code'
                        }, {
                            text: '版本',
                            width: 60,
                            sortable: true,
                            dataIndex: 'ver',
                            renderer: function(val) {
                                if (val)
                                    return "V" + val;
                            }
                        }, {
                            text: '文件名称',
                            width: 220,
                            sortable: true,
                            dataIndex: 'name',
                            renderer: showTitle
                        }, {
                            text: '附件',
                            width: 80,
                            sortable: true,
                            dataIndex: 'name',
                            renderer: function(value, p, record) {
                                if(value && record.get('file_ids')) {
                                    return "<img src='<?php echo HOME_PATH; ?>/public/images/icons/tick.png'></img>";
                                } else {
                                    return "<img src='<?php echo HOME_PATH; ?>/public/images/icons/cross.gif'></img>";
                                }
                            }
                        }, {
                            text: '状态',
                            width: 80,
                            dataIndex: 'state',
                            renderer: function(value, p, record) {
                                if ("Reviewing" == value) {
                                    p.css = "myreview";
                                    return "审核中";
                                }
                                if ("Return" == value) {
                                    return "退回";
                                }
                                if ("Active" == value) {
                                    return "已归档";
                                }
                                if ("Obsolete" === value) {
                                    return "旧版作废";
                                }
                                if ("Deleted" === value) {
                                    return "取消";
                                }
                                return value;
                            }
                        }, {
                            text: '审核阶段',
                            width: 200,
                            dataIndex: 'step_name',
                            renderer: showTitle
                        }, {
                            text: '审核情况',
                            width: 120,
                            dataIndex: 'review_state',
                            renderer: function(value, p, record) {
                                var tip = value.replace(/,/g, '<br />');
                                p.tdAttr = 'data-qtip="' + tip + '"';
                                return value;
                            }
                        }, {
                            text: '文件类别',
                            width: 180,
                            dataIndex: 'category_name',
                            renderer: showTitle
                        }, {
                            text: '分类名称',
                            width: 180,
                            dataIndex: 'type_name',
                            renderer: showTitle
                        }, {
                            text: '产品型号',
                            width: 100,
                            dataIndex: 'project_name',
                            renderer: showTitle
                        }, {
                            text: '项目信息',
                            width: 140,
                            hidden: true,
                            dataIndex: 'project_info',
                            renderer: showTitle
                        }, {
                            text: '关键字',
                            width: 140,
                            hidden: true,
                            dataIndex: 'tag',
                            renderer: showTitle
                        }, {
                            text: '文件描述',
                            width: 180,
                            dataIndex: 'description',
                            renderer: showTitle
                        }, {
                            text: '更改原因类型',
                            width: 160,
                            dataIndex: 'reason_type_name',
                            renderer: showTitle
                        }, {
                            text: '更改原因描述',
                            width: 140,
                            dataIndex: 'reason',
                            renderer: showTitle
                        }, {
                            text: '是否需要外发',
                            width: 100,
                            dataIndex: 'send_require',
                            renderer: viewBool
                        }, {
                            text: '备注',
                            width: 120,
                            dataIndex: 'remark',
                            renderer: showTitle
                        }, {
                            text: '归档时间',
                            width: 100,
                            dataIndex: 'archive_time',
                            renderer: Ext.util.Format.dateRenderer('Y-m-d H:i:s')
                        }, {
                            text: '申请人',
                            width: 100,
                            dataIndex: 'creater'
                        }, {
                            text: '申请时间',
                            width: 100,
                            dataIndex: 'create_time',
                            renderer: Ext.util.Format.dateRenderer('Y-m-d H:i:s')
                        }],
                    // paging bar on the bottom
                    bbar: Ext.create('Ext.PagingToolbar', {
                        store: filesStore,
                        displayInfo: true,
                        displayMsg: '显示 {0} - {1} 共 {2}',
                        emptyMsg: "没有数据",
                        items: [{
                            xtype: 'numberfield',
                            id: 'page_size_set',
                            value: 50,
                            width: 150,
                            hideTrigger: true,
                            labelAlign: 'right',
                            fieldLabel: '每页显示',
                            listeners: {
                            	specialKey :function(field,e){
                                    if (e.getKey() == Ext.EventObject.ENTER){
                                        var thisStore = this.up('pagingtoolbar').getStore();
                                        thisStore.pageSize = Ext.getCmp('page_size_set').getValue();
                                        thisStore.loadPage(1);
                                    }
                                }
                            }
                        }]
                    }),
                    listeners: {
                        itemdblclick: function(grid, rowIndex, e) {
                            viewAction(grid);
                        }
                    }
                });

                filesStore.on("beforeload", function() {
                    var search_tag = Ext.getCmp('search_tag').getValue();
                    var search_state = Ext.getCmp('search_state').getValue();
                    var search_archive_date_from = Ext.getCmp('search_archive_date_from').getValue();
                    var search_archive_date_to = Ext.getCmp('search_archive_date_to').getValue();
                    var search_category = Ext.getCmp('search_category').getValue();
                    Ext.apply(filesStore.proxy.extraParams, {
                        search_tag: search_tag,
                        search_state: search_state,
                        search_archive_date_from: search_archive_date_from,
                        search_archive_date_to: search_archive_date_to,
                        search_category: search_category
                    });
                });


                Ext.create('Ext.container.Viewport', {
                    layout: 'border',
                    border:0,
                    rtl: true,
                    items: [{
                            region: 'center',
                            border:0,
                            layout: 'fit',
                            items: [codePanel]
                        }]
                });
            });
            function closeWin(msg) {
                if(sendwin) {
            	    sendwin.close();
                }
            }
        </script>
    </head>
<body>
	<link
		href="<?php echo HOME_PATH ?>/public/js/uploadify/css/uploadify.css"
		rel="stylesheet" type="text/css" media="screen" />

	<script
		src="<?php echo HOME_PATH ?>/public/js/uploadify/scripts/jquery.uploadify.min.js"></script>
	<script
		src="<?php echo HOME_PATH ?>/public/js/uploadify/scripts/swfobject.js"></script>

</body>
</html>