<html>
<head>
<?php echo SYS_HEAD; ?>
<script type="text/javascript">
Ext.require([
    'Ext.data.*',
    'Ext.grid.*',
    'Ext.tree.*'
]);

Ext.onReady(function() {
    Ext.QuickTips.init();
    
    Ext.define('Account', {
        extend: 'Ext.data.Model',
        idProperty: 'id',
        fields: [{name: "id"}, 
                 {name: "active"}, 
                 {name: "parentId"}, 
                 {name: "code"}, 
                 {name: "name"}, 
                 {name: "description"}, 
                 {name: "remark"}, 
                 {name: "create_time",type: 'date',dateFormat: 'timestamp'}, 
                 {name: "update_time",type: 'date',dateFormat: 'timestamp'}, 
                 {name: "creater"}, 
                 {name: "updater"}]
    });
    
    var accountTreeStore = Ext.create('Ext.data.TreeStore', {
        model: 'Account',
        proxy: {
            type: 'ajax',
            reader: 'json',
            url: homePath+'/public/erp/fin_account/getaccount/option/data'
        },
        lazyFill: true
    });

    var tipRender = function(value,metaData,record,colIndex,store,view) {
        metaData.tdAttr = 'data-qtip="'+value+'"';
        return value;
    };
    
    var accountTreePanel = Ext.create('Ext.tree.Panel', {
        useArrows: true,
        border: 0,
        rootVisible: false,
        layout: 'fit',
        plugins: [
            Ext.create('Ext.grid.plugin.CellEditing', {
                clicksToEdit: 2
            })
        ],
        store: accountTreeStore,
        xtype: 'cell-editing',
        animate: false,
        viewConfig: {
            plugins: {
                ptype: 'treeviewdragdrop',
                containerScroll: true
            },
            getRowClass: function(record) {
                if(!record.get('active')){
                    // 当科目启用状态为false时，设置背景色
                    return 'gray-row';
                }else if(record.get('name') == '新科目'){
                    // 当新增科目未取名时，设置背景色
                    return 'light-red-row';
                }
            }
        },
        tbar: [{
            xtype: 'hiddenfield',
            id: 'finAccountExpand',
            value: 0
        }, {
        	iconCls: 'icon-view-expand',
        	id: 'expand_or_collapse',
        	text: '展开',
            scope: this,
            handler: function(){
                var btn = Ext.getCmp('expand_or_collapse');
                var finAccountExpand = Ext.getCmp('finAccountExpand').getValue();

                if(finAccountExpand == 0){
                	Ext.getCmp('finAccountExpand').setValue(1)
                	
                	accountTreePanel.expandAll();

                	btn.setIconCls('icon-view-collapse');
                	btn.setText('折叠');
                }else{
                	Ext.getCmp('finAccountExpand').setValue(0)
                	
                	accountTreePanel.collapseAll();

                	btn.setIconCls('icon-view-expand');
                	btn.setText('展开');
                }
            }
        }, {
            iconCls: 'icon-add',
            text: '添加科目',
            scope: this,
            handler: function(){
                var selModel = accountTreePanel.getSelectionModel();
                
                if(selModel.hasSelection()){
                    var selDataModel = selModel.getLastSelected();
                    var selNode = accountTreeStore.getNodeById(selDataModel.internalId);
                    
                    if(selNode != undefined && selNode.data['id'] != undefined){
                        // 当新增子节点时，如父节点原先没有子节点，则需要更新父节点Leaf属性
                        if(selNode.isLeaf()){
                            selNode.data['leaf'] = false;
                        }
    
                        // 新增节点
                        selNode.appendChild({
                            name: '新科目',
                            active: true,
                            leaf: true,
                            parentId: selNode.data['parentId']
                        });
    
                        // 新增节点自动展开
                        selNode.expand();
                    }else{
                        Ext.MessageBox.alert('提示', '请先保存新增上级科目信息！');
                    }
                }else{
                    var node = accountTreeStore.getRootNode();
                    node.appendChild({
                        name: '新科目',
                        active: true,
                        leaf: true,
                        parentId: 0
                    });
                }
            }
        }, {
            iconCls: 'icon-delete',
            text: '删除科目',
            scope: this,
            handler: function(){
                var selModel = accountTreePanel.getSelectionModel();
                
                if(selModel.hasSelection()){
                    var selDataModel = selModel.getLastSelected();
                    var selNode = accountTreeStore.getNodeById(selDataModel.internalId);

                    // 获取父节点
                    var parentNode = selNode.parentNode;

                    // 当父节点仅有一个子节点，修改父节点Leaf属性
                    if(parentNode.childNodes.length == 1){
                        parentNode.data['leaf'] = true;
                    }
                    
                    // 移除当前节点
                    selNode.remove();
                }else{
                    Ext.MessageBox.alert('提示', '没有选择删除对象！');
                }
            }
        }, {
            iconCls: 'icon-save',
            text: '保存修改',
            scope: this,
            handler: function(){
                var updateRecords = accountTreeStore.getUpdatedRecords();
                var insertRecords = accountTreeStore.getNewRecords();
                var deleteRecords = accountTreeStore.getRemovedRecords();

                // 判断是否有修改数据
                if(updateRecords.length + insertRecords.length + deleteRecords.length > 0){
                    var changeRows = {
                            updated:    [],
                            inserted:   [],
                            deleted:    []
                    }

                    // 判断科目名称是否有为空的情况
                    var valueCheck = true;
    
                    for(var i = 0; i < updateRecords.length; i++){
                        var data = updateRecords[i].data;
                        
                        if(data['code'] == '' || data['name'] == '' || data['name'] == '新科目'){
                            valueCheck = false;
                            break;
                        }
    
                        changeRows.updated.push(data)
                    }
    
                    for(var i = 0; i < insertRecords.length; i++){
                        var data = insertRecords[i].data;
                        
                        if(data['code'] == '' || data['name'] == '' || data['name'] == '新科目'){
                            valueCheck = false;
                            break;
                        }
    
                        changeRows.inserted.push(data)
                    }
    
                    for(var i = 0; i < deleteRecords.length; i++){
                        changeRows.deleted.push(deleteRecords[i].data)
                    }

                    // 格式正确则提交修改数据
                    if(valueCheck){
                        Ext.MessageBox.confirm('确认', '确定保存修改内容？', function(button, text){
                            if(button == 'yes'){
                                var json = Ext.JSON.encode(changeRows);
                                
                                Ext.Msg.wait('提交中，请稍后...', '提示');
                                Ext.Ajax.request({
                                    url: homePath+'/public/erp/fin_account/edit',
                                    params: {json: json},
                                    method: 'POST',
                                    success: function(response, options) {
                                        var data = Ext.JSON.decode(response.responseText);

                                        if(data.success){
                                            Ext.MessageBox.alert('提示', data.info);
                                            accountTreePanel.getSelectionModel().clearSelections();
                                            accountTreeStore.reload();
                                        }else{
                                            Ext.MessageBox.alert('错误', data.info);
                                        }
                                    },
                                    failure: function(response){
                                        Ext.MessageBox.alert('错误', '菜单获取失败');
                                    }
                                });
                            }
                        });
                    }else{
                        Ext.MessageBox.alert('提示', '科目名称不能为空或“新科目”！');
                    }
                }else{
                    Ext.MessageBox.alert('提示', '没有修改任何数据！');
                }
            }
        }, {
            iconCls: 'icon-refresh',
            text: '刷新',
            scope: this,
            handler: function(){accountTreeStore.reload();}
        }],
        columns: [{
            text: 'ID',
            hidden: true,
            dataIndex: 'id',
            flex: 0.2
        }, {
            xtype: 'treecolumn',
            text: '科目名称',
            flex: 1,
            sortable: true,
            dataIndex: 'name',
            editor: 'textfield'
        }, {
            xtype: 'treecolumn',
            text: '科目代码',
            flex: 1,
            sortable: true,
            dataIndex: 'code',
            editor: 'textfield'
        }, {
            xtype: 'checkcolumn',
            text: '启用状态',
            flex: 0.5,
            dataIndex: 'active',
            stopSelection: false
        }, {
            text: '描述',
            flex: 1.5,
            dataIndex: 'description',
            renderer: tipRender,
            editor: 'textfield'
        }, {
            text: '备注',
            flex: 2,
            dataIndex: 'remark',
            renderer: tipRender,
            editor: 'textfield'
        }, {
            text: '创建人',
            hidden: true,
            flex: 0.5,
            dataIndex: 'creater'
        }, {
            text: '创建时间',
            hidden: true,
            flex: 1,
            dataIndex: 'create_time',
            renderer : Ext.util.Format.dateRenderer('Y-m-d H:i:s')
        }, {
            text: '更新人',
            hidden: true,
            flex: 0.5,
            dataIndex: 'updater'
        }, {
            text: '更新时间',
            hidden: true,
            flex: 1,
            dataIndex: 'update_time',
            renderer : Ext.util.Format.dateRenderer('Y-m-d H:i:s')
        }],
        listeners: {
            'itemclick': function(treeview, record, item, index, e, opts){
                treeview.toggleOnDblClick = false;
                if(!record.get('leaf')){
                    var selModel = accountTreePanel.getSelectionModel();
                    var selDataModel = selModel.getLastSelected();
                    var selNode = accountTreeStore.getNodeById(selDataModel.internalId);

                    selNode.expand();
                }
            }
        }
    });
    
    Ext.create('Ext.container.Viewport', {
        layout: 'border',
        rtl: true,
        items: [{
        	border: 0,
            region: 'center',
            items:[accountTreePanel]
        }]
    });
});
</script>
</head>
<body>
</body>
</html>