<html>
<head>
<?php echo SYS_HEAD; ?>
<script type="text/javascript">
var user_id = <?php echo $this->user_id?>;
var accessViewTotal = <?php echo $this->accessViewTotal?>;

Ext.require([
    'Ext.*'
]);

Ext.define('Selection', {
    extend: 'Ext.data.Model',
    fields: [{name: 'id', type: 'int'},
             {name: 'currency_id', type: 'int'},
             {name: 'currency'},
             {name: 'type'},
             {name: 'code'},
             {name: 'name'},
             {name: 'symbol'},
             {name: 'text'},
             {name: 'rate'},
             {name: 'description'},
             {name: 'customer_code'},
             {name: 'customer_description'}]
});

//客户列表
var customerStore = Ext.create('Ext.data.Store', {
    model: 'Selection',
    proxy: {
       type: 'ajax',
       reader: 'json',
       url: homePath+'/public/erp/bpartner/getpartner/option/list/type/1'
    },
    autoLoad: true
});

// 币种
var currencyStore = Ext.create('Ext.data.Store', {
    model: 'Selection',
    proxy: {
       type: 'ajax',
       reader: 'json',
       url: homePath+'/public/erp/setting_currency/getcurrency/option/list'
    },
    autoLoad: true
});

// 仓库
var warehouseStore = Ext.create('Ext.data.Store', {
    model: 'Selection',
    proxy: {
        type: 'ajax',
        reader: 'json',
        url: homePath+'/public/erp/warehouse_index/getlist'
    },
    autoLoad: true
});

//仓库渲染
var warehouseRender = function(val){
	if(val != ''){
		index = warehouseStore.findExact('code',val);
        if (index != -1){
            rs = warehouseStore.getAt(index).data;
            return rs.name;
        }
        return val;
	}else{
		return '无';
	}
}

// 数据模型
Ext.define('Send', {
    extend: 'Ext.data.Model',
    fields: [{name: "id"},
             {name: "number"},
             {name: "order_number"},
             {name: 'customer_id', type: 'int'},
             {name: "customer"},
             {name: "date",type: 'date',dateFormat: 'Y-m-d'},
             {name: "total"},
             {name: "description"},
             {name: "remark"},
             {name: "create_time",type:'date',dateFormat: 'timestamp'},
             {name: "update_time",type:'date',dateFormat: 'timestamp'},
             {name: "creater"},
             {name: "updater"}]
});

// 数据源
var sendStore = Ext.create('Ext.data.Store', {
    model: 'Send',
    pageSize: 50,
    proxy: {
        type: 'ajax',
        reader: {
            type: 'json',
            root: 'rows',
            totalProperty: 'total'
        },
        url: homePath+'/public/erp/stock_send/getsend'
    },
    listeners: {
    	beforeload: loadSend
    }
});

function loadSend(){
	var key = Ext.getCmp('search_key').getValue();
	var date_from = Ext.Date.format(Ext.getCmp('search_date_from').getValue(), 'Y-m-d');
    var date_to = Ext.Date.format(Ext.getCmp('search_date_to').getValue(), 'Y-m-d');
    
	Ext.apply(sendStore.proxy.extraParams, {
		key: key,
		date_from: date_from,
		date_to: date_to
    });
};

//获取货币符号
function setMoney(val, currency){
	var symbol = '';
	
    currencyStore.each(function(rec) {
	    if (rec.get('name') == currency) {
	    	symbol = rec.get('symbol');
	    }
	});
    
    return Ext.util.Format.currency(val, symbol, 2);
}

var required = '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>';

</script>
<script type="text/javascript" src="<?php echo HOME_PATH?>/library/LodopFuncs.js"></script>
<script type="text/javascript" src="<?php echo HOME_PATH?>/application/modules/erp/views/scripts/stock/send/js/order_list.js"></script>
<script type="text/javascript" src="<?php echo HOME_PATH?>/application/modules/erp/views/scripts/stock/send/js/items.js"></script>
<script type="text/javascript">

// 显示查看窗口
function openView(idx){
	sendWin.show();
	itemsForm.getForm().reset();
    var record = sendStore.getAt(idx);
    itemsForm.getForm().loadRecord(record);
    sendWin.setTitle('销售交货');
    Ext.getCmp('sendSaveBtn').disable();
	Ext.getCmp('itemsSelectBtn').disable();
	Ext.getCmp('itemsDeleteBtn').disable();
	Ext.getCmp('print_preview').enable();

	itemsStore.load({
        params: {
        	send_id: record.get('id')
        }
    });
}

var totalColumn = Ext.create('Ext.grid.column.Column', {
	text: '金额',
    dataIndex: 'total',
    renderer: function(value, meta, rec){
        return setMoney(value, rec.get('currency'));
    },
    flex: 1
});

var sendGrid = Ext.create('Ext.grid.Panel', {
    border: 0,
	store: sendStore,
	id: 'sendGrid',
    columnLines: true,
    tbar: [{
        xtype: 'datefield',
        format: 'Y-m-d',
        width: 100,
        id: 'search_date_from',
        emptyText: '日期从...'
    }, {
        xtype: 'datefield',
        format: 'Y-m-d',
        width: 100,
        id: 'search_date_to',
        emptyText: '日期至...'
    }, {
        xtype: 'textfield',
        id: 'search_key',
        emptyText: '关键字...',
        listeners: {
        	specialKey :function(field,e){
                if (e.getKey() == Ext.EventObject.ENTER){
                	sendStore.loadPage(1);
                }
            }
        }
    }, {
        xtype: 'splitbutton',
        text: '查询',
        iconCls: 'icon-search',
        handler: function(){
        	sendStore.loadPage(1);
        },
        menu: [{
            text: '导出',
            iconCls: 'icon-export',
            handler: function(){
                var key = Ext.getCmp('search_key').getValue();
            	var date_from = Ext.Date.format(Ext.getCmp('search_date_from').getValue(), 'Y-m-d');
                var date_to = Ext.Date.format(Ext.getCmp('search_date_to').getValue(), 'Y-m-d');
                
            	window.open(homePath+'/public/erp/stock_send/getsend/option/csv/key/' + key + '/date_from/' + date_from + '/date_to/'+ date_to);
            }
        }]
    }, {
        //xtype: 'splitbutton',
        text: '销售交货',
        iconCls: 'icon-doc',
        handler: function(){
        	sendWin.show();

        	Ext.getCmp('sendSaveBtn').enable();
        	Ext.getCmp('itemsSelectBtn').enable();
        	Ext.getCmp('itemsDeleteBtn').enable();
        	Ext.getCmp('print_preview').disable();

        	itemsStore.loadData([],false);
        	Ext.getCmp('itemsForm').getForm().reset();
        	Ext.getCmp('operate').setValue('new');
        }
    }, '->', {
        text: '刷新',
        iconCls: 'icon-refresh',
        handler: function(){
        	sendStore.reload();
        }
    }],
    columns: [{
        xtype: 'rownumberer'
    }, {
        text: 'ID',
        align: 'center',
        hidden: true,
        dataIndex: 'id'
    }, {
        text: '交货单号',
        align: 'center',
        dataIndex: 'number',
        width: 120
    }, {
        text: '销售订单',
        align: 'center',
        dataIndex: 'order_number',
        width: 140
    }, {
        text: '客户',
        dataIndex: 'customer',
        width: 220
    }, {
        text: '交货日期',
        dataIndex: 'date',
        align: 'center',
        renderer: Ext.util.Format.dateRenderer('Y-m-d'),
        width: 90
    }, /* {
        text: '金额',
        dataIndex: 'total',
        renderer: function(value, meta, rec){
            return setMoney(value, rec.get('currency'));
        },
        flex: 1
    },  */{
        text: '描述',
        dataIndex: 'description',
        flex: 3
    }, {
        text: '备注',
        dataIndex: 'remark',
        flex: 3
    }, {
        text: '交货人',
        dataIndex: 'creater',
        align: 'center',
        flex: 1
    }, {
        text: '交货时间',
        dataIndex: 'create_time',
        align: 'center',
        renderer : Ext.util.Format.dateRenderer('Y-m-d H:i:s'),
        width: 140
    }, {
        text: '更新人',
        hidden: true,
        dataIndex: 'updater',
        align: 'center',
        flex: 1
    }, {
        text: '更新时间',
        hidden: true,
        dataIndex: 'update_time',
        align: 'center',
        renderer : Ext.util.Format.dateRenderer('Y-m-d H:i:s'),
        width: 140
    }],
    listeners: {
        itemdblclick: function( grid, record, item, index, e, eOpts ) {
        	openView(index);
        }
    },
    bbar: Ext.create('Ext.PagingToolbar', {
    	border: 0,
        store: sendStore,
        displayInfo: true,
        displayMsg: '显示 {0} - {1} 共 {2}',
        emptyMsg: "没有数据"
    })
});

Ext.onReady(function() {
    Ext.QuickTips.init();
    
    Ext.state.Manager.setProvider(Ext.create('Ext.state.CookieProvider'));
    
    Ext.create('Ext.Viewport', {
        layout: 'border',
        items: [{
            region: 'center',
            layout: 'fit',
            border: 0,
            items: [sendGrid]
        }]
    });

    if(accessViewTotal){
    	Ext.getCmp('sendGrid').getView().headerCt.insert(4, totalColumn);
    }

    sendStore.loadPage(1);
});
</script>
</head>
<body>
</body>
</html>